runtime: nodejs14
default_expiration: '360d'
automatic_scaling:
  max_instances: 1
handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
  - url: /(.*\.(gif|png|jpg|css|js|svg|ico))$
    static_files: www/\1
    upload: www/.*\.(gif|png|jpg|css|js|svg|ico)$
    expiration: '300d'
